include:
 - board: nice_nano
   shield: split_dongle
   snippet: studio-rpc-usb-uart
 - board: nice_nano
   shield: split_left
   cmake-args: -DCONFIG_ZMK_SPLIT=Y DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_STUDIO=y
 - board: nice_nano
   shield: right 
